version: '3.8'

services:
  postgres:
    image: docker.io/library/postgres:18
    container_name: gold-vpn-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - type: volume
        source: pg 
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
      - type: bind
        source: ./secrets/db_password
        target: /run/secrets/db_password
        read_only: true
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U goldvpn"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: gold-vpn-backend
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      RUST_LOG: debug
    volumes:
      - type: bind
        source: ./secrets/db_password
        target: /run/secrets/db_password
        read_only: true
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - postgres
    mem_limit: 256m
    cpus: "0.5"

volumes:
  pg:
    driver:
      local

networks:
  backend:
    internal: true
